version: 2.1

orbs:
  android: circleci/android@0.2.1

jobs:
  build:
    docker:
      - image: circleci/android:api-28

    steps:
      - checkout

      - android/install-ndk

      - run:
          command: ./gradlew build
