/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ekutt_example_imageconverter_ImageConverter */

#ifndef _Included_com_ekutt_example_imageconverter_ImageConverter
#define _Included_com_ekutt_example_imageconverter_ImageConverter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ekutt_example_imageconverter_ImageConverter
 * Method:    convertJPEGtoPNG_Native
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_ekutt_example_imageconverter_ImageConverter_convertJPEGtoPNG_1Native
(JNIEnv *, jclass, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
